//TODO define log-macros in external file... use glog instead? (inf-50)
#define LOGEXEC(msg) printf("\n[%d]::%s : %d\n", QTime::currentTime().msecsSinceStartOfDay(),(msg), __LINE__)
#define LOGERR(msg) printf("\n[%d]:ERROR!!!:: %s : %d\n", QTime::currentTime().msecsSinceStartOfDay(),(msg), __LINE__)
// activeCaptureCmd.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <QtWidgets/QApplication>
#include "StandardProjector.h"
#include "AcquisitionDeviceManager.h"
#include "activeCaptureCmd.h"
enum class ParamCase {
	DEFAULT,
	CAMERA_CONFIGS,
	PROJECTION_CONFIGS,
	OUTPUT_FOLDER
};

using namespace std;

static void printHelp()
{
	//TODO Complete helptext here!! Example of config files (inf+1)
	printf("\nUsage:\n\nactiveAcquisition.exe -p [PathToProjectedPictures] [PathToProjectionSettingsFile] [selectedScreen: {0,1,2}, def:1] -c [pathToCameraSettingsFile] -o [ExistingOutputFolder]\n\n");
	printf("\n---ProjectionSettingsFile: text file, each line is as follows: [pictureFileName],[projectedTimeInMicroseconds],[1|0 indicating triggering of connected cameras]\n");
	printf("\n---CameraSettingsFile: xml file for AVT Cameras, the format is the same generated by the VIMBA Viewer proprietary software\n");
		//, "Example:\n\n");
}

void initActiveCapture(int nCamsToConfigure, string cameraXmls[], int nProjectors, string projectionsFolder[], string projectionsConfig[],
	int projectionScreen[], string outputFolder)
{
	//Procedure:
	/*
	1. Initialize selected APIS (vimba, no need x canon/nikon/dlp)
	2. select upto nCams vimba from identified list
	3. load xmls to vimba
	
	In parallel (?)
	2. identify  nProjectors < # of screens
	3. Load pictures x each projectionsFolder
	4. Load Projections config. to ProjectorClass - get total projection time.

	then:

	5. set #pictures to capture in AVT Cams to match longest projection total time + alpha.
	6. avts -> start capturing & start projecting
	7. transfer captured pictures to output folder
	8. write xml output with capturing data (compliant with 3digify format!)
	
	*/
	//1.


	/*
	//The following is working fine so far.
	*/

	AcquisitionDeviceManager *mng = new AcquisitionDeviceManager();//API Inintialization is into the constructor
	mng->detectCameras();

	int nCams = nCamsToConfigure > mng->getCountCameras() ?mng->getCountCameras() : nCamsToConfigure;


	printf("There are %d detected cams and I'm trying to load %d xml files", mng->getCountCameras(), nCamsToConfigure);

	for (int i = 0;i < nCams;i++)
	{
		AVTCamera *ac = mng->getCamera(0);
		bool result = ac->loadSettings(cameraXmls[i]);
		printf("loading for cam # %d: %s\n", i, result ? "true" : "false");
	}
}
int main(int argc, char *argv[])//multiple avt cameras
{

}

int mainSingleAVTCapture(int argc, char *argv[])//SingleAVTCapture
{
	QApplication a(argc, argv);
	printf("# args: %d\n", argc);
	for (int i = 1;i < argc;i++)
	{
		printf(argv[i]);
		printf(" ");
	}
	ParamCase paramCase = ParamCase::DEFAULT;
	int countParamCase = 0;
	int countProjectors = 0;

	int nCams = 0;
	string cameraConfigXml[5];//max 5 cams
	string projectionsFolder[2];//Path to the folder with pngs to be projected. max 2 projs (projector + mask)
	string projectionsConfig[2];//text files with configuration of time x each projection.
	int projectionScreen[2] = { 1,2 };//screen identfier, 2nd and 3rd screen by default.
	string outputFolder = "./";


	//WF: 1. Parse parameters
	for (int i = 1;i < argc;i++)
	{
		if (argv[i][0] == '-')
		{
			//param=param.substr(1, param.size());
			if (!_strnicmp("-h", argv[i], 2))
			{
				printHelp();
				break;
			}
			else if (!_strnicmp("-c", argv[i], 2))
			{
				paramCase = ParamCase::CAMERA_CONFIGS;
			}
			else if (!_strnicmp("-p", argv[i], 2))
			{
				paramCase = ParamCase::PROJECTION_CONFIGS;
				countProjectors++;
			}
			else if (!_strnicmp("-o", argv[i], 2))
			{
				paramCase = ParamCase::OUTPUT_FOLDER;
			}
			countParamCase = 0;
			continue;
		}
		string param(argv[i]);

		switch (paramCase)
		{
		case ParamCase::DEFAULT:
			printf("Wrong arguments");
			printHelp();
			break;


		case ParamCase::CAMERA_CONFIGS:
			cameraConfigXml[countParamCase] = param;
			nCams++;
			break;
		case ParamCase::PROJECTION_CONFIGS:
			switch (countParamCase)
			{
			case 0:
				projectionsFolder[countProjectors - 1] = param;
				break;
			case 1:
				projectionsConfig[countProjectors - 1] = param;
				break;
			case 2:
				int screenId = (atoi(argv[i]));
				projectionScreen[countProjectors - 1] = screenId;
			}
			break;
		case ParamCase::OUTPUT_FOLDER:
			outputFolder = param;
			break;
		
		}
		countParamCase++;

	}
	
	AcquisitionDeviceManager *mng = new AcquisitionDeviceManager();

	////WF: 2. Initialize & configure desired projectors (extra screens)
	//TODO Create as many standardProjectors as configured by parameter. countProjectors
	StandardProjector iv;//important to call in main function (or keep the reference to iv)	
	int c = iv.loadProjectionsFolder(projectionsFolder[0].c_str());
	iv.loadProjectionSettings(projectionsConfig[0].c_str());
	iv.showInFullProjection(projectionScreen[0]);
	
	////WF: 3. Detect all avt cameras, configure with passed configuration file & prepare for capturing

	std::vector<AVTCamera*> cameraList = mng->detectAVTCameras();
	if (cameraList.size() == 0)
	{
		printf("\nno AVT Cameras detected. Enter to continue");
	}
	else {
		//TODO Do the loop for all identified cameras.
		bool res = cameraList[0]->loadSettings(cameraConfigXml[0]);
		res ? printf("xml load succeeded\n") : printf("something failed loading camera settings");
		cameraList[0]->setOutputFolder(outputFolder);
		VmbErrorType err = cameraList[0]->prepareCapture();

		if (VmbErrorSuccess != err)
		{
			printf("something wrong preparing the capture");
			return err;
		}

		////WF: 4. register cameras as observers of the master(first) projector (if multiple projectors, one is master, others should be slaves as well!!)
		for (int i = 0;i<cameraList.size();i++)
		{
			iv.registerCameraObserver(cameraList[i]);
		}
		//TODO: Register slave projectors as observers of main projector.

		////WF: 5. Play synchronized projections:
		//TODO: read and use # of repetitions as parameter of program.		
		iv.playProjectionSequence(1);

		//TODO: SOFTWARE REFACTORS:: Support canons and use register them as camera observers. Check if this can work with CAMERA class as registered observers instead of AVTCAMERA
	}



	//TODO safe termination of program:
	//CMD CLOSE:http://www.cplusplus.com/reference/cstdlib/atexit/
	//QT Window close:https://stackoverflow.com/questions/8165487/how-to-do-cleaning-up-on-exit-in-qt
	//int result = 0;
	printf("\n\njust before executing!\n\n");
	int result = a.exec();	
	
	printf("\n\n\nenter to finish!\n\n");
	fflush(stdout);
	cin.get();
	printf("just before delete manager\n\n");
	delete mng;
	return result;
	
}
